-- =============================================================================
-- deploy.sql — Master orchestrator for Legal Doc AI Demo
--
-- ⚠️ NON-PRODUCTION SAMPLE. SE demo only — not for production deployment.
-- ⚠️ Suggested rotation: re-deploy fresh every 30 days; teardown when done.
--
-- Owner: john.kang@snowflake.com (sfc-gh-jkang)
-- Verified GA on AWS US East 1 as of May 2026. Cortex AI feature regional
-- availability changes — check current status before deploying:
--   https://docs.snowflake.com/en/user-guide/snowflake-cortex/aisql
--   https://docs.snowflake.com/en/user-guide/snowflake-cortex/cortex-search
--   https://docs.snowflake.com/en/user-guide/snowflake-cortex/cortex-agents
--
-- Connection: substitute your own Snowflake CLI alias (this repo's author uses `aws_spcs`)
--
-- All `CREATE` statements use `IF NOT EXISTS` or `OR REPLACE` — re-running
-- this deploy is idempotent and will not clobber a customer's existing
-- SNOWFLAKE_EXAMPLE database (only the LEGAL_DOC_AI_DEMO schema is touched).
--
-- Usage (run each file in order):
--   # one-time prereqs (ACCOUNTADMIN; safe to re-run):
--   snow sql -f sql/00_prereqs.sql -c <your-connection>
--
--   # core demo:
--   for f in sql/01_setup.sql sql/02_stage.sql sql/03_pdf_corpus.sql \
--            sql/10_baseline.sql sql/11_cache_layer.sql sql/12_smart_routing.sql \
--            sql/13_cheap_scorer.sql sql/14_structured_outputs.sql \
--            sql/15_embed_search.sql sql/16_agent.sql sql/20_cost_telemetry.sql; do
--     snow sql -f "$f" -c <your-connection>
--   done
--
--   # optional Lever 10 spend guardrails (compile-only by default — DDL is in
--   # /* */ blocks; uncomment in your fork before running):
--   snow sql -f sql/30_resource_monitor.sql -c <your-connection>
--
-- Or via SnowSQL (supports !source):
--   !source sql/00_prereqs.sql
--   !source sql/01_setup.sql
--   !source sql/02_stage.sql
--   !source sql/03_pdf_corpus.sql
--   !source sql/10_baseline.sql
--   !source sql/11_cache_layer.sql
--   !source sql/12_smart_routing.sql
--   !source sql/13_cheap_scorer.sql
--   !source sql/14_structured_outputs.sql
--   !source sql/15_embed_search.sql
--   !source sql/16_agent.sql
--   !source sql/20_cost_telemetry.sql
--   !source sql/30_resource_monitor.sql   -- optional, compile-only by default
--
-- Prerequisites:
--   1. Run sql/00_prereqs.sql once as ACCOUNTADMIN to create
--      PYPI_ACCESS_INTEGRATION (Streamlit Container Runtime needs it).
--   2. Run scripts/fetch_corpus.py to download public PDFs from govinfo.gov
--   3. Run scripts/upload_pdfs.py to upload them to @PDF_STAGE
-- =============================================================================
