-- =============================================================================
-- teardown.sql — Clean removal of all Legal Doc AI Demo objects
-- Usage: snow sql -f teardown.sql -c aws_spcs
-- =============================================================================
USE ROLE SYSADMIN;

-- Agent
DROP AGENT IF EXISTS SNOWFLAKE_EXAMPLE.LEGAL_DOC_AI_DEMO.LEGAL_DOC_AI_AGENT;

-- Search service
DROP CORTEX SEARCH SERVICE IF EXISTS SNOWFLAKE_EXAMPLE.LEGAL_DOC_AI_DEMO.LEGAL_DOC_AI_SEARCH;

-- Tables
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.LEGAL_DOC_AI_DEMO.LEGAL_CHUNKS;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.LEGAL_DOC_AI_DEMO.STRUCTURED_AB;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.LEGAL_DOC_AI_DEMO.SCORER_AB;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.LEGAL_DOC_AI_DEMO.ROUTING_LOG;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.LEGAL_DOC_AI_DEMO.PARSED_CACHE;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.LEGAL_DOC_AI_DEMO.BASELINE_RESULTS;

-- Views
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.LEGAL_DOC_AI_DEMO.DAILY_AI_COST;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.LEGAL_DOC_AI_DEMO.LEVER_SAVINGS;

-- Procedures
DROP PROCEDURE IF EXISTS SNOWFLAKE_EXAMPLE.LEGAL_DOC_AI_DEMO.BASELINE_PROCESS_DOC(STRING);
DROP PROCEDURE IF EXISTS SNOWFLAKE_EXAMPLE.LEGAL_DOC_AI_DEMO.PARSE_WITH_CACHE(STRING, STRING);
DROP PROCEDURE IF EXISTS SNOWFLAKE_EXAMPLE.LEGAL_DOC_AI_DEMO.SMART_PARSE(STRING);
DROP PROCEDURE IF EXISTS SNOWFLAKE_EXAMPLE.LEGAL_DOC_AI_DEMO.RUN_SCORER_MATRIX(ARRAY);
DROP PROCEDURE IF EXISTS SNOWFLAKE_EXAMPLE.LEGAL_DOC_AI_DEMO.SCORE_STRUCTURED(STRING);
DROP PROCEDURE IF EXISTS SNOWFLAKE_EXAMPLE.LEGAL_DOC_AI_DEMO.SCORE_FREETEXT(STRING);
DROP PROCEDURE IF EXISTS SNOWFLAKE_EXAMPLE.LEGAL_DOC_AI_DEMO.CHUNK_AND_EMBED(STRING);

-- Stage
DROP STAGE IF EXISTS SNOWFLAKE_EXAMPLE.LEGAL_DOC_AI_DEMO.PDF_STAGE;

-- Schema
DROP SCHEMA IF EXISTS SNOWFLAKE_EXAMPLE.LEGAL_DOC_AI_DEMO;

-- Warehouse
DROP WAREHOUSE IF EXISTS SFE_LEGAL_DOC_AI_WH;

-- Compute pool
DROP COMPUTE POOL IF EXISTS SFE_LEGAL_DOC_AI_POOL;

-- Role (must be SECURITYADMIN to drop)
USE ROLE SECURITYADMIN;
DROP ROLE IF EXISTS LEGAL_DOC_AI_RL;
